#!/usr/bin/env python3
"""gen_header.py — turn a plain-text corpus into src/corpus_klingon.h

Usage:
    python tools/gen_header.py input.txt src/corpus_klingon.h

The engine is char-level, so it will learn whatever characters your text
contains. Keep the vocabulary small (<= NV, default 32) for a tiny model.

Code generated by AI (Claude) under the direction of Carlos Lopez Andres
(Codix Labs). License: Apache 2.0.
"""
import sys

def escape(text: str) -> str:
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    return "".join(out)

def main():
    if len(sys.argv) != 3:
        print("usage: python gen_header.py input.txt output.h")
        sys.exit(1)
    src, dst = sys.argv[1], sys.argv[2]
    raw = open(src, encoding="utf-8").read().replace("\r", "")
    chunk = 2000  # split the string literal so compilers don't choke
    lines = [
        "// Generated by tools/gen_header.py — do not edit by hand.",
        "#pragma once",
        f"#define KLIN_CORPUS_LEN {len(raw)}",
        "static const char KLIN_CORPUS[] =",
    ]
    for i in range(0, len(raw), chunk):
        lines.append('"%s"' % escape(raw[i:i + chunk]))
    lines.append(";")
    open(dst, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print(f"wrote {dst}: {len(raw)} chars, vocab {len(set(raw))}")

if __name__ == "__main__":
    main()
